...
let indexLength = this.fulltextIndex.documentStore.length
...
let keywordDocFreq = this.freqIndex[keyword.ngram].f
...
let length = content.split(' ').length
...
let keywordIdf = 1 + Math.log((1 + indexLength) / (1 + keywordDocFreq))
...
let keywordTf = keyword.count 
...
let lengthNorm = 1 / length
...
let score = keywordTf * keywordIdf * lengthNorm
...