FROM node:7.8

RUN mkdir -p /usr/src/app
RUN mkdir -p ~/.ssh
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN ssh-keyscan -H gitlab.enterpriselab.ch >> ~/.ssh/known_hosts
RUN chmod +x keys/setup-ssh.sh
RUN sh keys/setup-ssh.sh

RUN npm -v
RUN npm install
RUN npm run grunt
RUN npm update

EXPOSE 3012
CMD [ "npm", "start" ]
