before_script:
 - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

 - eval $(ssh-agent -s)
 
 - ssh-add <(echo "$SSH_PRIVATE_KEY")

 - mkdir -p ~/.ssh
 - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
- deploy

deploy-all:
 image: jmfirth/webpack
 stage: deploy
 script:
 - apt-get update
 - apt-get install git -y
 - git config --global push.default simple
 - git branch -a

push-prod:
 stage: deploy
 script:
 - git push dokku@dev-ikc.el.eee.intern:index-service refs/remotes/origin/master:master
 only:
 - master
