...
this.sftp.readdir(path, (err: any, list: any) =
    ...
});
...
this.sftp.readFile(path, (err:any, buffer:any) => {
    ...
})
...
this.sftp.writeFile(path, buffer, (err: any) => {
    ...
});
...