...
this.conn.exec(("mkdir -p " + path), (err: any, stream: any) => {
    ...
})
...
this.conn.exec(("ls -d -1 " + path), (err: any, stream: any) => {
    ...
    stream.on('data', function (data: any) {
        ...
    }).on("end", () => {
        ...
        paths.split('\n')
        ...
    })
    ...
})
...
this.conn.exec(("find -newer " + path + " -type f "), (err: any, stream: any) => {
    ...
    stream.on('data', function (data: any) {
        ...
    }).on("end", () => {
        ...
        paths.split('\n')
        ...
    })
    ...
})
...